### ISSUE TITLE
weighfit algorithm breakthrough

### ISSUE THREAD

**Issue by sprintup** [iOSDevClass/WeighFit#15]
instead of breaking down the app into meals (as this is already a contrived abstraction), lets assume simply that the user ought to consume a defined amount of calories at any point during the day. 

- a function that returns the amount of calories user ought to have consumed at any particular time in the day. No meal name. For instance, at 6:00pm user ought to have consumed 75% or calories (1800 hrs / 2400 hrs), meaning on a 3000 daily caloric target, at 6:00, user ought to have consumed 2250 calories. Obviously, if user is a certain amount outside this number, they're to find equilibrium. 
- function to run on viewwillload so every time user opens app, it tells him/her exactly where they're at relative to their optimal weight goal track. 
- notifications alert user if they fall too far outside their equilibrium.

**Comment by brandevnull** [comment]
I think this makes sense.
